SELECT 
    ROUND(AVG(FISH_LENGTH.LENGTH), 2) AS AVERAGE_LENGTH
FROM (
    SELECT
        CASE WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
        END AS LENGTH
    FROM 
        FISH_INFO
) FISH_LENGTH