SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE * J.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN 
    FOOD_ORDER J 
    ON P.PRODUCT_ID = J.PRODUCT_ID
WHERE
    YEAR(J.PRODUCE_DATE) = 2022
    AND MONTH(J.PRODUCE_DATE) = 5
GROUP BY 
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY 
    TOTAL_SALES DESC,
    P.PRODUCT_ID