-- 코드를 입력하세요
SELECT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND H.START_DATE >= '2022-10-01' 
AND H.START_DATE < '2022-11-01' 
GROUP BY h.CAR_ID
ORDER BY h.CAR_ID DESC